# Generated by Django 6.1 on 2026-09-01 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wellness', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wellnesslog',
            name='device_name',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='wellnesslog',
            name='heart_rate',
            field=models.PositiveIntegerField(default=72),
        ),
    ]
