# Generated by Django 6.1 on 2026-09-01 17:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wellness', '0002_wellnesslog_device_name_wellnesslog_heart_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wellnesslog',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
