# Generated by Django 6.1 on 2026-09-04 08:55

import datetime
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReactionTrial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.UUIDField(default=uuid.uuid4)),
                ('trial_num', models.IntegerField()),
                ('reaction_ms', models.FloatField()),
                ('is_valid', models.BooleanField(default=True)),
                ('is_practice', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reaction_trials', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['session_id', 'trial_num'],
            },
        ),
        migrations.CreateModel(
            name='UserBaseline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hrv_baseline', models.FloatField(blank=True, null=True)),
                ('rhr_baseline', models.FloatField(blank=True, null=True)),
                ('reaction_baseline', models.FloatField(blank=True, null=True)),
                ('sleep_baseline', models.FloatField(blank=True, null=True)),
                ('training_load_baseline', models.FloatField(blank=True, null=True)),
                ('subjective_baseline', models.FloatField(blank=True, null=True)),
                ('valid_days_count', models.IntegerField(default=0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='neuro_baseline', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WorkoutOutcome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today)),
                ('readiness_before', models.FloatField()),
                ('recommended_intensity', models.CharField(default='', max_length=30)),
                ('actual_duration', models.IntegerField(blank=True, null=True)),
                ('actual_rpe', models.IntegerField(blank=True, null=True)),
                ('performance_rating', models.IntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workout_outcomes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='DailyReadiness',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today)),
                ('sleep_hours', models.FloatField(blank=True, null=True)),
                ('sleep_quality', models.IntegerField(blank=True, null=True)),
                ('hrv', models.FloatField(blank=True, null=True)),
                ('resting_heart_rate', models.IntegerField(blank=True, null=True)),
                ('reaction_time_ms', models.FloatField(blank=True, null=True)),
                ('reaction_variability', models.FloatField(blank=True, null=True)),
                ('energy', models.IntegerField(blank=True, null=True)),
                ('focus', models.IntegerField(blank=True, null=True)),
                ('muscle_fatigue', models.IntegerField(blank=True, null=True)),
                ('workout_duration', models.IntegerField(blank=True, null=True)),
                ('workout_rpe', models.IntegerField(blank=True, null=True)),
                ('sleep_score', models.FloatField(blank=True, null=True)),
                ('hrv_score', models.FloatField(blank=True, null=True)),
                ('rhr_score', models.FloatField(blank=True, null=True)),
                ('reaction_score', models.FloatField(blank=True, null=True)),
                ('subjective_score', models.FloatField(blank=True, null=True)),
                ('training_load_score', models.FloatField(blank=True, null=True)),
                ('calculated_score', models.FloatField(blank=True, null=True)),
                ('final_score', models.FloatField(blank=True, null=True)),
                ('readiness_category', models.CharField(blank=True, default='', max_length=20)),
                ('safety_override', models.BooleanField(default=False)),
                ('safety_flags', models.JSONField(blank=True, default=list)),
                ('baseline_confidence', models.CharField(blank=True, default='LOW', max_length=10)),
                ('missing_data', models.JSONField(blank=True, default=list)),
                ('explanation', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readiness_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Daily readiness records',
                'ordering': ['-date'],
                'unique_together': {('user', 'date')},
            },
        ),
    ]
