# Generated by Django 6.1 on 2026-08-26 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WorkoutLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('duration_minutes', models.PositiveIntegerField()),
                ('difficulty_feedback', models.CharField(blank=True, max_length=50, null=True)),
                ('xp_earned', models.PositiveIntegerField(default=100)),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
