# Generated by Django 6.1 on 2026-09-01 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_profile_extra_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='dietaryprofile',
            name='water_target_ml',
            field=models.PositiveIntegerField(blank=True, default=2500),
        ),
        migrations.AddField(
            model_name='fitnessprofile',
            name='age_group',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='fitnessprofile',
            name='notifications',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='fitnessprofile',
            name='preferred_location',
            field=models.CharField(blank=True, default='home', max_length=50),
        ),
    ]
